repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
#     -   id: check-json
    -   id: check-yaml
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
- repo: https://github.com/Venkat6506/nodejs_website.git
  rev: v4.3.0
  sha: main
  hooks:
    - id: snyk-audit
