repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
#     -   id: check-json
    -   id: check-yaml
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
-   repo: https://github.com/Venkat6506/nodejs_website
    rev: 1.1.0
    hooks:
    - id: snyk-test
