name: A2Z_WORKFLOW
on: workflow_dispatch
jobs:   
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: c
      uses: actions/checkout@v3
    - name: npm install, build
      run: |
        sudo apt install nodejs -y 
        sudo apt install npm -y
        npm install
        npm run build --if-present
    - name: Upload Articats
      uses: actions/upload-artifact@v3
      with:
        name: kvg
        path: ./
#     - name: Deploy to my EC2 instance
#       uses: easingthemes/ssh-deploy@v2.1.5
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#           SOURCE: "./"
#           REMOTE_HOST: "ec2-54-90-39-95.compute-1.amazonaws.com"
#           REMOTE_USER: "ubuntu"
#           TARGET: "/home/ubuntu/nodejs_website"
        
  POST_CD:
    
    name: POST_CD
    runs-on: ubuntu-latest
    needs: CI
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: kvg
        path: ./
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-54-90-39-95.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/nodejs_website"
