name: A2Z_WORKFLOW
on: workflow_dispatch
jobs:
  CI:
    name: CI
    runs-on: self-hosted
    steps:
    - name: c
      uses: actions/checkout@v3
    - name: npm install, build
      run: |
        sudo apt install nodejs -y 
        sudo apt install npm -y
        npm install
        npm run build --if-present
    - name: Upload Articats
      uses: actions/upload-artifact@v3
      with:
        name: kvg
        path: ./
  CD:
    name: CD
    runs-on: self-hosted
    needs: CI
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: kvg
        path: /home/ubuntu/nodejs_website
        
  PRECOMMIT:
    name: PRECOMMIT
    runs-on: self-hosted
    needs: CD
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
#     - uses: pre-commit/action@v3.0.0 # need to uncomment to run pre-commit.
    
  SONARQUBE:
    name: SAST_SCAN_SONARQUBE
    runs-on: self-hosted
    needs: PRECOMMIT
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}

  OWASP:
    name: OWASP_ZAP_SCAN
#     runs-on: self-hosted
    runs-on: ubuntu-latest
    needs: SONARQUBE
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://54.90.39.95:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
