name: hvg
on: push
jobs:
  build-pro:
    name: bp
    runs-on: ubuntu-latest
    steps:
    - name: c
      uses: actions/checkout@v3
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: kvg
        path: ./
  rep:
    name: rp
    runs-on: ubuntu-latest
    needs: build-pro
    steps:
    - name: da
      uses: actions/download-artifact@v3
      with:
        name: kvg
    - name: test
      run: ls -R
      
    
    
  
