name: hvg
on: push
jobs:
  build-pro:
    name: bp
    runs-on: ubuntu-latest
    steps:
    - name: c
      uses: actions/checkout@v3
    - name: INs
      run: npm install
    - name: bpj
      run: npm run build
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: kvg
        path: ./
  rep:
    name: rp
    runs-on: ubuntu-latest
    needs: build-pro
    steps:
    - name: da
      uses: actions/download-artifact@v3
      with:
        name: kvg
    - name: test
      run: ls -R
      
    
    
  
