name: CICD 
on: workflow_dispatch
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: c
      uses: actions/checkout@v3
    - name: npm install, build
      run: |
        sudo apt install nodejs -y 
        sudo apt install npm -y
        npm install
        npm run build --if-present
    - name: Upload Articats
      uses: actions/upload-artifact@v3
      with:
        name: kvg
        path: ./
  CD:
    name: CD
    runs-on: self-hosted
    needs: CI
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: kvg
        path: /home/ubuntu/
    - name: test
      run: ls -R
    - name: Running Applicaion
      run: |
        sudo npm install pm2 -g
        pm2 start app.js -f
    
    
  
