name: test

on: workflow_dispatch

permissions:
  id-token: write # this permission is required to authorize the request for the GitHub OIDC token used by the configure-aws-credentials action

jobs:
  start-runners:
    name: Provision self-hosted runners
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}

      - name: Scale up ECS service
        uses: Enterprise-CMCS/ecs-scale-service@main
        with:
          cluster: "gh-runner"
          service: "gh-runner"
          desired-count: 2

  test-self-hosted:
    name: Testing self-hosted tag
    needs: start-runners
    runs-on: self-hosted
    steps:
      - name: step 1
        run: echo "Hello World!"

  stop-runners:
    name: Deprovision self-hosted runners
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE_ARN }}

      - name: Scale down ECS service
        uses: Enterprise-CMCS/ecs-scale-service@main
        with:
          cluster: "gh-runner"
          service: "gh-runner"
          desired-count: 0
