name: DevSecOps pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run pre-commit hooks
      run: npx pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Check test coverage
      run: npm run coverage
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run SAST scan
      run: npx snyk test
  sca:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run SCA scan
      run: npx npm-audit
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run Sonar scan
      run: npx sonar-scanner
  owasp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Run OWASP scan
      run: npx owasp-scanner
