name: OWASP ZAP SCAN
on: workflow_dispatch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           ref: main
#       - name: ZAP Scan
#         uses: zaproxy/action-full-scan@v0.4.0
#         with:
#           docker_name: 'owasp/zap2docker-stable'
#           target: 'http://54.173.254.181:3000/'
#           rules_file_name: '.zap/rules.tsv'
#           cmd_options: '-a'
  
        - name: polaris scan SAST
          uses: sukot1/polaris-codescanner@v0.01
          with:
            POLARIS_SERVER_URL: "https://scan.coverity.com/"
            POLARIS_ACCESS_TOKEN: "IO6pUJB6BRZ7b8OKGf5l5g"
            POLARIS_PROJECT_NAME: "Venkat6506/nodejs_website"
            POLARIS_PROJECT_BRANCH: "main"
