name: CI Dooer
on: push
jobs:
  coverity_polaris_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Polaris tests
        uses: loadbalancerorg/polaris-action@v1.1
        with: 
          server_url: "https://scan.coverity.com/projects/venkat6506-nodejs_website"
          access_token: "IO6pUJB6BRZ7b8OKGf5l5g"
          total_issues: 5
          new_issues: 4
          cli_scan_json_file: .synopsys/polaris/cli-scan.json
          
          
          
