name: Node.js CI
on: workflow_dispatch
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
         
    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npx eslint .

    - name: Test
      run: npm run test
