name: Precommit Scan
on: workflow_dispatch

jobs:
  pre-commit:
    runs-on: ubuntu-latest
#     runs-on: v1
    steps:
    - uses: actions/checkout@v3
    - name: mode1
      run: ls -l
    - name: mode2
      run: pwd
    - name: mode
      run: chmod 777 /home/runner/work/nodejs_website/nodejs_website
    - name: mode3
      run: ls -l
    - name: mode4
      run: chmod 777 hooks
    - name: mode5
      run: ls -l
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
